### ISSUE TITLE
Major: Searching when Soundcloud is checked does not find results

### ISSUE THREAD

**Issue by corstena** [cue-music/cue-music#2]
Description: **Only breaks when using Mozilla Firefox** Searching with the Soundcloud option selected will not produce any results. Searching for a song with only Youtube selected will produce results, but searching with Youtube and Soundcloud or just Soundcloud alone will not produce results. 

Steps to Reproduce:
1. With only Soundcloud selected, search "Travis Scott".
2. After waiting for about 10 seconds, no results will appear.
3. De-select Soundcloud and only select Youtube.
4. Search for "Travis Scott".
5. The Youtube Results will populate.

Expected Results:
Results for either just Soundcloud or both Soundcloud and Youtube appear.

Actual Results:
If the option for Soundcloud is enabled, no results will load at all.

Error Logs:
When opening the console, the major error occurring is a Cross-Origin Request Block. The exact error is:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://api.soundcloud.com/tracks?client_id=9cfb13e8afddd6b2ffcf8902b1dfe087&q=pnbrock. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘(null)’).

Reason for error:
This sort of protection is built into web browsers to prevent websites from sending requests to other websites on a users behalf in case the website is sending malicious requests. It is done to prevent Cross-Site Request Forgery Attacks (CSRF). You can read up more about this type of attack at the following link:

https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)

**Comment by AlexBieg** [comment]
I belive this error is actually due to another #1. The problem is that for some reason you need to click twice on the search button before the results show up. When I do this in firefox it does display results (See picture). 

![capture](https://cloud.githubusercontent.com/assets/11547509/26808111/875f16f2-4a0f-11e7-838e-9e6f9a85826b.PNG)
