### ISSUE TITLE
Major: Playlist sharing link does not work

### ISSUE THREAD

**Issue by zmbc** [cue-music/cue-music#3]
Steps:
- Create a playlist
- Add some songs
- Click the share button
- Receive a URL like "http://students.washington.edu/?user=bMWQJRaNc8aHZwnpDUulvBcC20k2&playlist=undefined"
- Go to this URL
- See the generic "UW Students Web Server" page

**Comment by tgents** [comment]
I have the same issue as well.

**Comment by YvonneIngles** [comment]
I have the same issue
